/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nyldons;


import nyldons.compare.NyldonComparator;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.List;

public class App {

    private final NyldonGenerator gen;

    public static void main(String[] args) {

        var comp = Setting.getComparator();
        var max = Setting.maxLength;

        new App(comp, max).run();
    }

    public App(NyldonComparator comp, int maxLength) {
        this.gen = new NyldonGenerator(comp, maxLength);
    }

    public void run() {
        var nyldon = gen.generate();

        try {
            writeToFile(nyldon);
        } catch (IOException e) {
            System.err.println("Error while writing to file");
            e.printStackTrace();
        }
    }


    private static void writeToFile(List<String> nyldon) throws IOException {
        Path path = Setting.getOutputFilePath();

        Files.createDirectories(path.getParent());

        try (var writer = Files.newBufferedWriter(path, StandardOpenOption.CREATE, StandardOpenOption.WRITE)) {
            for (String word : nyldon) {
                writer.write(word);
                writer.newLine();
            }
        }
    }





}
