/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nyldons;


import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.List;

public class App {


    public static void main(String[] args) throws IOException {

        var comp = Setting.getComparator();
        var max = Setting.maxLength;
        var gen = new NyldonGenerator(comp, max);

        var nyldon = gen.generate();

        writeToFile(nyldon);
    }

    private static void writeToFile(List<String> nyldon) throws IOException {
        Path path = Setting.getOutputFilePath();

        Files.createDirectories(path.getParent());

        try (var writer = Files.newBufferedWriter(path, StandardOpenOption.CREATE, StandardOpenOption.WRITE)) {
            for (String word : nyldon) {
                writer.write(word);
                writer.newLine();
            }
        }
    }


}
